import { describe, expect, test } from "bun:test";

import { catalog } from "./catalog";
import { schemas } from "./index";

const iso = "2026-09-12T00:00:00.000Z";
const epoch = 1_757_616_000_000;

const mailNode = {
  id: "mail_1",
  accountEmail: "me@kreyon.in",
  to: ["alex@example.com"],
  cc: [] as string[],
  bcc: [] as string[],
  subject: "Hello",
  body: "Body",
  status: "draft",
  createdAt: iso,
  updatedAt: iso,
};

const valid = {
  ErrorBody: { error: "Invalid JSON body" },
  ServerLog: {
    id: "log_1",
    at: epoch,
    kind: "job",
    level: "info",
    title: "queued",
    body: "",
  },
  CollectedError: { id: "err_1", message: "boom", createdAt: epoch },
  CollectErrorInput: { message: "boom" },
  HealthResponse: {
    ok: true,
    service: "aira-on-cloud",
    authRequired: false,
    scheduler: true,
    console: true,
    gmail: false,
    workersAi: { accountConfigured: true, tokenConfigured: true, model: "@cf/qwen/qwen3-30b-a3b-fp8" },
  },
  ListQuery: {},
  PageContext: { url: "https://example.com", title: "Example" },
  JobToolCall: { name: "websearch", arguments: "{}", result: null },
  Job: {
    id: "job_1",
    clientId: "ext_1",
    status: "queued",
    text: "hi",
    createdAt: epoch,
    updatedAt: epoch,
  },
  JobEvent: {
    id: "jevt_1",
    jobId: "job_1",
    at: epoch,
    kind: "thinking",
    message: "planning",
  },
  AskRequest: { text: "  hello  " },
  AskResponse: { jobId: "job_1", status: "queued" },
  JobHttpResponse: { jobId: "job_1", status: "done", text: "hello", clientId: "ext_1" },
  QuestionOption: { id: "opt_1", label: "Yes" },
  WidgetAction: { id: "link_1", label: "Open", kind: "link" },
  Widget: { title: "Hi", body: "There" },
  QuestionReply: { optionId: "opt_1" },
  AgentRunResult: { content: "done", skillId: "mail" },
  ClientMessage: { type: "hello", clientId: "ext_1" },
  ServerMessage: { type: "accepted", jobId: "job_1" },
  RequestContext: {},
  ImportanceScore: { score: 40, label: "low", reasons: ["default outbound weight"], scoredAt: iso },
  MailTemplate: {
    id: "tpl_1",
    name: "Demo",
    subjectTemplate: "Hi",
    bodyMarkdown: "Hello",
    variables: [],
    createdAt: iso,
    updatedAt: iso,
  },
  MailNode: mailNode,
  RecentMailCard: {
    id: "msg_1",
    from: "a@example.com",
    fromName: "A",
    subject: "Hi",
    preview: "Hello",
    date: "Fri, 11 Sep 2026 10:00:00 -0700",
  },
  MailBoard: { drafts: [mailNode], scheduled: [], recent: [] },
  SendDraftResult: { alreadySent: true, draft: mailNode },
  GmailStatus: {
    configured: false,
    connected: false,
    email: null,
    scopes: [],
    redirectUri: null,
  },
  GmailMessage: {
    id: "msg_1",
    threadId: "th_1",
    snippet: "Hi",
    from: "a@example.com",
    to: "me@kreyon.in",
    subject: "Hello",
    date: "Fri, 11 Sep 2026 10:00:00 -0700",
  },
  GmailMessageDetail: {
    id: "msg_1",
    threadId: "th_1",
    snippet: "Hi",
    from: "a@example.com",
    to: "me@kreyon.in",
    subject: "Hello",
    date: "Fri, 11 Sep 2026 10:00:00 -0700",
    body: "Hello",
    labelIds: ["INBOX"],
  },
  WatchCondition: { path: "pageProps.grant.isPaused", op: "eq", value: "false" },
  Watcher: {
    id: "watch_1",
    title: "Grants",
    prompt: "check",
    resourceUrl: "https://example.com/data.json",
    conditions: [{ path: "pageProps.grant.isPaused", op: "eq", value: "false" }],
    intervalMinutes: 30,
    notifyEmail: true,
    notifyWidget: true,
    status: "active",
    nextCheckAt: epoch,
    createdAt: epoch,
    updatedAt: epoch,
  },
  WatcherWrite: {
    title: "Grants",
    resourceUrl: "https://example.com/data.json",
    conditions: [{ path: "pageProps.grant.isPaused", op: "eq" }],
  },
  NotifyEvent: {
    id: "nq_1",
    title: "Fired",
    body: "paused",
    status: "pending",
    emailSent: false,
    widgetSent: false,
    createdAt: epoch,
  },
  ScheduledTask: {
    id: "task_1",
    title: "Send",
    prompt: "send the draft",
    runAt: iso,
    status: "pending",
    createdAt: iso,
    updatedAt: iso,
  },
  ScheduleWrite: { title: "Send", prompt: "send the draft", delayMinutes: 5 },
  ScheduleMetadata: { mailAction: "send_draft", draftId: "mail_1" },
  SkillEdge: { to: "mail", kind: "routes-to" },
  Skill: {
    id: "mail",
    name: "Mail",
    description: "Send mail",
    tags: ["mail"],
    instructions: "Write drafts",
    tools: ["ask_user"],
    edges: [],
    updatedAt: epoch,
  },
  SkillMeta: {
    id: "mail",
    name: "Mail",
    description: "Send mail",
    tags: ["mail"],
    tools: ["ask_user"],
    edges: [],
  },
  SkillWrite: {},
  Canvas: { id: "cv_1", title: "Answer", markdown: "# Hi", createdAt: iso },
  CanvasWrite: { markdown: "# Hi" },
  CanvasListItem: {
    id: "cv_1",
    title: "Answer",
    createdAt: iso,
    expiresAt: iso,
    url: "/r/cv_1",
  },
  ToolResult: { ok: true, id: "page_1", extra: "kept" },
  NotionRef: { id: "page_1" },
} satisfies Record<keyof typeof schemas, unknown>;

const reject = {
  ErrorBody: { error: "" },
  ServerLog: { id: "log_1", at: epoch, kind: "job", level: "debug", title: "", body: "" },
  CollectedError: { id: "err_1", message: "   ", createdAt: epoch },
  CollectErrorInput: { message: "   " },
  HealthResponse: {
    ok: false,
    service: "aira-on-cloud",
    authRequired: false,
    scheduler: true,
    console: true,
    gmail: false,
    workersAi: { accountConfigured: true, tokenConfigured: true, model: "x" },
  },
  ListQuery: { limit: 0 },
  PageContext: { url: "", title: "Example" },
  JobToolCall: { name: "", arguments: "{}", result: null },
  Job: {
    id: "job_1",
    clientId: "ext_1",
    status: "queued",
    text: "hi",
    createdAt: "now",
    updatedAt: epoch,
  },
  JobEvent: {
    id: "jevt_1",
    jobId: "job_1",
    at: epoch,
    kind: "widget",
    message: "nope",
  },
  AskRequest: { text: "   " },
  AskResponse: { jobId: "job_1", status: "pending" },
  JobHttpResponse: { jobId: "job_1", status: "pending" },
  QuestionOption: { id: "opt_1", label: "" },
  WidgetAction: { id: "link_1", label: "Open", kind: "submit" },
  Widget: { title: "Hi" },
  QuestionReply: {},
  AgentRunResult: { content: "done" },
  ClientMessage: { type: "hello" },
  ServerMessage: { type: "accepted" },
  RequestContext: { clientId: 1 },
  ImportanceScore: { score: 101, label: "low", reasons: [], scoredAt: iso },
  MailTemplate: {
    id: "tpl_1",
    name: "",
    subjectTemplate: "Hi",
    bodyMarkdown: "Hello",
    variables: [],
    createdAt: iso,
    updatedAt: iso,
  },
  MailNode: { ...mailNode, to: [] },
  RecentMailCard: {
    id: "",
    from: "a@example.com",
    fromName: "A",
    subject: "Hi",
    preview: "Hello",
    date: "Fri",
  },
  MailBoard: { drafts: [], scheduled: [], recent: "nope" },
  SendDraftResult: { alreadySent: true },
  GmailStatus: {
    configured: false,
    connected: false,
    email: null,
    scopes: [],
  },
  GmailMessage: {
    id: "",
    threadId: "th_1",
    snippet: "Hi",
    from: "a@example.com",
    to: "me@kreyon.in",
    subject: "Hello",
    date: "Fri",
  },
  GmailMessageDetail: {
    id: "msg_1",
    threadId: "th_1",
    snippet: "Hi",
    from: "a@example.com",
    to: "me@kreyon.in",
    subject: "Hello",
    date: "Fri",
    body: "Hello",
  },
  WatchCondition: { path: "pageProps.x", op: "equals" },
  Watcher: {
    id: "watch_1",
    title: "Grants",
    prompt: "check",
    resourceUrl: "https://example.com/data.json",
    conditions: [],
    intervalMinutes: 30,
    notifyEmail: true,
    notifyWidget: true,
    status: "active",
    nextCheckAt: epoch,
    createdAt: epoch,
    updatedAt: epoch,
  },
  WatcherWrite: {
    title: "Grants",
    resourceUrl: "not-a-url",
    conditions: [{ path: "pageProps.x", op: "eq" }],
  },
  NotifyEvent: {
    id: "nq_1",
    title: "Fired",
    body: "paused",
    status: "queued",
    emailSent: false,
    widgetSent: false,
    createdAt: epoch,
  },
  ScheduledTask: {
    id: "task_1",
    title: "Send",
    prompt: "send the draft",
    runAt: "tomorrow",
    status: "pending",
    createdAt: iso,
    updatedAt: iso,
  },
  ScheduleWrite: { title: "Send", prompt: "send the draft" },
  ScheduleMetadata: { mailAction: "delete" },
  SkillEdge: { to: "mail", kind: "depends-on" },
  Skill: {
    id: "mail",
    name: "Mail",
    description: "Send mail",
    tags: ["mail"],
    instructions: "Write drafts",
    tools: ["ask_user"],
    edges: [],
    updatedAt: "now",
  },
  SkillMeta: {
    id: "mail",
    name: "",
    description: "Send mail",
    tags: ["mail"],
    tools: ["ask_user"],
    edges: [],
  },
  SkillWrite: { name: "   " },
  Canvas: { id: "cv_1", title: "Answer", markdown: "# Hi", createdAt: "today" },
  CanvasWrite: { markdown: "" },
  CanvasListItem: {
    id: "cv_1",
    title: "Answer",
    createdAt: iso,
    expiresAt: iso,
  },
  ToolResult: { ok: "true" },
  NotionRef: { id: "" },
} satisfies Record<keyof typeof schemas, unknown>;

describe("public schemas", () => {
  test("catalog length matches public registry size", () => {
    expect(catalog.length).toBe(Object.keys(schemas).length);
  });

  test("catalog schemaName set matches public registry keys", () => {
    const registryNames = Object.keys(schemas).sort();
    const catalogNames = catalog.map((row) => row.schemaName).sort();
    expect(catalogNames).toEqual(registryNames);
  });

  test("each public schema accepts a valid fixture and rejects a bad one", () => {
    for (const name of Object.keys(schemas) as Array<keyof typeof schemas>) {
      const schema = schemas[name];
      const ok = schema.safeParse(valid[name]);
      expect(ok.success, `${String(name)} valid`).toBe(true);
      const bad = schema.safeParse(reject[name]);
      expect(bad.success, `${String(name)} reject`).toBe(false);
    }
  });
});
